server:
  port: 8180
spring:
  datasource:
    url: jdbc:h2:file:C:/data/camunda-db-spr-for
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true